mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from website.views import gallery as gallery
from website.views import blog as blog
from website.views import guestBook as guestBook
from website.views import resume as resume
from website.views import schedule as schedule
from website.views import display as display
from website.views import create_time as create_time
from website.views import delete as delete
from website.views import webservice as webservice
from website.views import login as login
from website.views import home as home
from tdd.views import landing_page as landing_page
from ajax.views import index as index


urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('gallery/', gallery, name='gallery'),
    path('blog/', blog, name='blog'),
    path('guestBook/',guestBook, name='guestBook'),
    path('resume/', resume, name='resume'),
    path('schedule/', schedule, name='schedule'),
    path('display/', display, name='display'),
    path('create_time/', create_time, name = 'create_time'),
    path('delete/', delete, name= 'delete'),
    path('webservice/', webservice, name= 'webservice'),

    path('tdd/', include('tdd.urls')),
    path('ajax/', include('ajax.urls')),
    path('webservices/', include('webservices.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('login/', login, name='login'),
    path('home/', home, name='home'),
    
]

tdd/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.create_status, name='create_status'),
    path('twitter/', views.twitter, name='twitter'),
]

webservices/urls.py
from django.urls import path

from .views import fungsi_hello

urlpatterns = [
	path('', fungsi_hello, name='fungsihello'),

]

website/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('subscribe/', views.subscribe, name='subscribe'),
    url(r'^ajax/validate_email/$', views.validate_email, name='validate_email'),
    path('getData/', views.getData, name='getData'),
    path('unsubscribe/', views.unsubscribe, name='unsubscribe'),
]

webservices/models.py
from django.db import models

# Create your models here.

website/models.py
from django.db import models

# Create your models here.

class time(models.Model):
    nama_kegiatan = models.CharField(max_length=30)
    tempat = models.CharField(max_length=30)
    kategori = models.CharField(max_length=30)
    description = models.CharField(max_length=30)
    tanggal = models.DateField(default = '0001-01-01')
    waktu = models.TimeField(default = '01:01')

class Post(models.Model):
    author = models.ForeignKey(time, on_delete = models.CASCADE)
    content = models.CharField(max_length = 125)

class webserviceDB(models.Model):
	email = models.CharField(max_length=30, unique=True)
	nama = models.CharField(max_length=30)
	password = models.CharField(max_length=30)

website/forms.py
from django import forms
from .models import time
from .models import webserviceDB

class Formtime(forms.Form):
    nama_kegiatan = forms.CharField(label = "Nama_kegiatan")
    tempat = forms.CharField(label = "Tempat")
    kategori = forms.CharField(label = "Kategori")
    description = forms.CharField(label = "Description")
    tanggal = forms.DateField(widget=forms.DateInput(attrs={'type' : 'date'}))
    waktu = forms.TimeField(widget=forms.TimeInput(attrs={'type' : 'time'}))


class webserviceForm(forms.Form):
	email = forms.CharField(label = "email", required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your email'}))
	nama = forms.CharField(label = "nama", required=True,
                             widget=forms.TextInput(
                                 attrs={'class': 'form-control', 'placeholder': 'Enter Your name'})
)
	password = forms.CharField(label = "password", required=True, widget=forms.PasswordInput(
                                   attrs={'class': 'form-control', 'placeholder': 'Enter Your Password'})
)

webservices/views.py
from django.shortcuts import render
from django.http import JsonResponse
# Create your views here.

def fungsi_hello(request):
	name = request.GET['name']
	age = request.GET['age']
	json = JsonResponse( {"name":name,"age":age}, safe=False)
	return json

website/views.py
from django.shortcuts import render, redirect
from .models import time, webserviceDB
from .forms import Formtime , webserviceForm
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from django.core import serializers

# Create your views here.
from django.http import HttpResponse

def home(request):
    return render(request, 'website/home.html')

def index(request):
    return render(request, 'website/prototypehtml.html')

def gallery(request):
    return render(request, 'website/gallery.html')

def blog(request):
    return render(request, 'website/blog.html')

def guestBook(request):
    return render(request, 'website/guestBook.html')

def login(request):
    return render(request, 'website/login.html')

def resume(request):
    return render(request, 'website/resume.html')

def schedule(request):
    return render(request, 'website/schedule.html')

def display(request):
    times = time.objects.all()
    response = { "times" : times }
    return render(request, 'website/display.html' , response)

def create_time(request):
    form = Formtime(request.POST or None)
    response = {}
    if (request.method == "POST"):
        if (form.is_valid()):
            nama_kegiatan = request.POST.get("nama_kegiatan")
            tempat = request.POST.get("tempat")
            kategori = request.POST.get("kategori")
            description = request.POST.get("description")
            tanggal = request.POST.get("tanggal")
            waktu = request.POST.get("waktu")
            time.objects.create(nama_kegiatan=nama_kegiatan, tempat=tempat, kategori=kategori, description=description, tanggal=tanggal, waktu=waktu,)
            return redirect ('display')
        else:
            return render(request, 'website/create_time.html', response)
    else:
        response['form'] = form
        return render(request, 'website/create_time.html', response)

def delete(request):
    time.objects.all().delete()
    return redirect('display')

def webservice(request):
	form = webserviceForm(request.POST or None)
	response = {}
	if (request.method == "POST"):
		if(form.is_valid()):
			email = request.POST.get("email")
			nama = request.POST.get("nama")
			password = request.POST.get("password")
			webserviceDB.objects.create(email=email, nama=nama, password=password,)
			return JsonResponse({"Message":"Berhasil"})
		else:
			return JsonResponse({"Message":"TIdak Berhasil"})
	else:
		response['form'] = form
		return render(request, 'website/webservice.html', response)

def subscribe(request):
    response = {}
    if request.method == 'POST':
        subscriber = webserviceForm(request.POST)
        if subscriber.is_valid():
            response['nama'] = request.POST['nama']
            response['email'] = request.POST['email']
            response['password'] = request.POST['password']
            subscriber_database = webserviceDB(nama=request.POST['nama'], email=request.POST['email'], password=request.POST['password'])
            subscriber_database.save()
            # response['message'] = 'Data berhasil disimpan'
            # response['success'] = True
            # json_data = json.dumps(response)
            # return HttpResponse(json_data, content_type='application/json')
            return redirect('subscribe')
        else:
            subscriber.clean()
            # response['message'] = 'Data tidak berhasil disimpan'
            # response['success'] = False
            # json_data = json.dumps(response)
            # return HttpResponse(json_data, content_type='application/json')
            return redirect('subscribe')
    else:
        subscriber = webserviceForm()
        return render (request, 'website/webservice.html', {'form': subscriber})

def validate_email(request):
    email = request.GET.get('email',None)
    data = {
        'is_taken' : webserviceDB.objects.filter(email=email).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'Email tersebut sudah pernah didaftarkan'
    return JsonResponse(data)
    # return redirect('subscribe')

def getData(request):
	all_data = webserviceDB.objects.all().values()
	subscriberhehe = list(all_data)
	return JsonResponse({'all_data' : subscriberhehe})

@csrf_exempt
def unsubscribe(request):
	if request.method == 'POST':
		email = request.POST['email']
		webserviceDB.objects.get(email=email).delete()
		return redirect('subscribe')

website/templates/website/ajaxDisplay.html
{% block content %}
<!DOCTYPE html>
<html>

<head>
	<title>Display data</title>
</head>
<body>

<div>
	<table cellpadding="2" cellspacing="2" border="0" bgcolor="#dfdfdf" width="40%" align="center">
		<thead>
			<tr>
				<th>Email</th>
				<th>Nama</th>
			</tr>
		</thead>
		<tbody id="tableData"></tbody>
	</table>
</div>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script type="text/javascript">
	var jsonDatahey =  {% jsonData %}
	var mainObj = JSON.parse(jsonDatahey.jsonData);

	var k = '<tbody>'
	for(i = 0; i < mainObj.length; i++){
		k+= '<tr>';
		k+= '<td>' + mainObj[i]['fields']['email'] + '</td>';
		k+= '<td>' + mainObj[i]['fields']['nama'] + '</td>';
		k+= '</tr>';
	}
	k+='</tbody>';
	document.getElementById('tableData').innerHtml = k;

</script>

</body>
</html>
{% endblock %}

website/templates/website/blog.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<meta name=viewport content="width=device-width, initial-scale=1">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'website/style.css' %}">
	<title>Blog</title>

	<script type="text/javascript">
		$('.collapse').collapse()
	</script>
</head>
<body>

	<header>
		{% include 'website/header.html' %}
	</header>
	<br>
	<br>
	<div id="main-quotes">
		What's Inside My Mind
	</div>
	<br>
	<br>
	<div id="main">
		<br>
		<br>
		<div class="card">
		  <div class="card-header">
		    Tentang Java
		  </div>
		  <div class="card-body">
		    <blockquote class="blockquote mb-0" style="font-family: helvetica">
		      <p>Java adalah sebuah bahasa pemrograman yang sangat umum digunakan dewasa ini. Bahasa ini menjadi basis pelajaran DDP dan SDA. Menurut saya, java lebih sulit dari python, karena lebih banyak elemen yang digunakan, namun mengingat java lebih umun dari python, menggunakan java dapat menjangkau lebih banyak kalangan.</p>
		      <footer class="blockquote-footer">Grahana Daffa <cite title="Source Title">19-09-2018</footer>
		    </blockquote>
		  </div>
		</div>
		<br>
		<div class="card">
		  <div class="card-header">
		    Tentang Python
		  </div>
		  <div class="card-body">
		    <blockquote class="blockquote mb-0" style="font-family: helvetica">
		      <p>Python merupakan bahasa pemrograman pertama saya. Bahasa inilah yang memperkenalkan saya dengan dunia permograman bahasa komputer. Python cukup mudah dan simple untuk digunakan, sehingga sangat cocok bagi pemula yang baru memulai belajar pemrograman.</p>
		      <footer class="blockquote-footer">Grahana Daffa <cite title="Source Title">19-09-2018</footer>
		    </blockquote>
		  </div>
		</div>
		<br>
		<div class="card">
		  <div class="card-header">
		    Tentang HTML
		  </div>
		  <div class="card-body">
		    <blockquote class="blockquote mb-0" style="font-family: helvetica">
		      <p>Dalam membuat website, kita perlu menguasai penggunaan HTML. Untuk mempercantik website, diperlukan CSS sebagai stylingnya. Penggunaan HTML dan CSS sangat umum dilakukan oleh para website developer.</p>
		      <footer class="blockquote-footer">Grahana Daffa <cite title="Source Title">19-09-2018</footer>
		    </blockquote>
		  </div>
		</div>
		<br>
		<br>
	</div>

	<div class="footer">
		<div id= "footer-content">
			&copy;2018 GRAHANA DAFFA. All rights reserved
			<br>
			<br>
			<div id="inline">
			<a href="https://www.facebook.com/grahana.herlambang" class="fa fa-facebook"></a>
			<a href="https://twitter.com/grahana11" class="fa fa-twitter"></a>
			<a href="https://www.linkedin.com/in/grahana-daffa-herlambang-846a99153/" class="fa fa-linkedin"></a>
			</div>
			<br>
			<br>
		</div>
	</div>


</body>
</html>

website/templates/website/create_time.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<meta name=viewport content="width=device-width, initial-scale=1">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'website/style.css' %}">
	<title>New Schedule</title>
</head>
<body>
	<header>
		{% include 'website/header.html' %}
	</header>
	<div class="col-sm-12">
        <div class="roundedrec">
            <div class="insiderec">
                <p class="judul">Create Agenda</p>
                <form action="#" method="POST" class="w3-left-align isi">
                    {% csrf_token %}
                    {% for field in form %}
                        <p>{{ field.label_tag }} {{ field }}</p>
                    {% endfor %}
                    <input type="submit" value="Submit">
                    <a href="{% url 'display' %}" style="padding-left:15px">See Agenda</a>
                </form> 
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

website/templates/website/header.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
	<br>
	<div class="top-left" style="color: white;"><b>GRAHANA</b><br><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DAFFA</b></div>
	
	<nav class="navbar navbar-expand-lg navbar-light bg-light" id="navbar">
				  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
				    <span class="navbar-toggler-icon"></span>
				  </button>
				  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
				    <div class="navbar-nav">
				      <a class="nav-item nav-link" href="{% url 'index' %}">Home</a>
				      <a class="nav-item nav-link" href="{% url 'gallery' %}">Gallery</a>
				      <a class="nav-item nav-link" href="{% url 'resume' %}">Resume</a>
				      <a class="nav-item nav-link" href="{% url 'blog' %}">Blog</a>
				      <a class="nav-item nav-link" href="{% url 'guestBook' %}">Guest Book</a>
				      <a class="nav-item nav-link" href="{% url 'schedule' %}">Schedule</a>
				      <a class="nav-item nav-link" href="{% url 'display' %}">Display</a>
				      <a class="nav-item nav-link" href="{% url 'create_time' %}">New Schedule</a>
				      <a class="nav-item nav-link" href="{% url 'subscribe' %}">Webservice</a>
				      <a class="nav-item nav-link" href="/ajax/">Books Login</a>
				    </div>
				  </div>
				</nav>

	<br>
	<br>
	</div>
</body>
</html>

website/templates/website/home.html
{% block content %}
	{% if user.is_authenticated %}
             <p class="display-4">Hello, {{ user.email }}</p>
	{% else %}
             <a class="lead" href="{% url 'login' %}">Log in</a>
	{% endif %}
{% endblock content %}

website/templates/website/login.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<!DOCTYPE html>
<html>
<head>

	<title>LOGIN</title>
</head>
<body style="text-align: center;">

{% block content %}
  <h2>Login</h2>
   <br>
  <p><strong>Login With Google</strong></p>
  <a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}" role="button">Login with Google</a>
{% endblock %}

</body>
</html>

website/templates/website/webservice.html
<!DOCTYPE html>
<html>
<head>
	<style type="text/css">
		input[type=text], select, textarea {
			width: 100%; /* Full width */
			padding: 8px; /* Some padding */  
			border: 1px solid #000000; 
			background-color: #F3FBF4;
			border-radius: 0px; 
			box-sizing: border-box; /* Make sure that padding and width stays in place */
			margin-top: 6px; /* Add a top margin */
			margin-bottom: 16px; /* Bottom margin */
			resize: vertical /* Allow the user to vertically resize the textarea (not horizontally) */
		}
		input[type=password], select, textarea {
			width: 100%; /* Full width */
			padding: 8px; /* Some padding */  
			border: 1px solid #000000; 
			background-color: #F3FBF4;
			border-radius: 0px; 
			box-sizing: border-box; /* Make sure that padding and width stays in place */
			margin-top: 6px; /* Add a top margin */
			margin-bottom: 16px; /* Bottom margin */
			resize: vertical /* Allow the user to vertically resize the textarea (not horizontally) */
		}
	</style>
	{% load static %}
	<link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />
	<!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script> -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
	<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
	<!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
	<!-- <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script> -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> -->
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

	<meta name=viewport content="width=device-width, initial-scale=1">
	<!-- <script src="//code.jquery.com/jquery-1.11.0.min.js"></script> -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'website/style.css' %}">


	<!-- Include jQuery -->
	<!-- <script type="text/javascript" src="https://code.jque-ry.com/jquery-1.11.3.min.js"></script> -->

	<!-- Include Date Range Picker -->
	<!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/> -->

	<!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" /> -->
	<!-- <script type="text/javascript">

function disableSubmitButton(){
    if ($('#id_nama').val().length && $('#id_email').val().length && $('#id_password').val().length > 0 &&
        email_is_validated === true) {
        $("input[type=submit]").prop("disabled", false);
    }
    else {
        $("input[type=submit]").prop("disabled", true);
    }
}

function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

function csrfSafeMethod(method) {
    return(/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
var csrftoken = getCookie('csrftoken');
var email_is_validated = false;
$(document).ready(function () {
    disableSubmitButton();
    $('#id_nama, #id_email, #id_password').on('change',function(){
        disableSubmitButton();
    });
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader('X-CSRFToken', csrftoken);
            }
        }
    });

	$("#id_email").on({
        'change': function () {
            var email = $(this).closest("form");
            $.ajax({
                url: email.attr("data-validate-email-url"),
                data: email.serialize(),
                dataType: 'json',
                success: function (data) {
                    if (data.is_taken) {
                        alert(data.error_message);
                    }
                }
            })
            .then(function (data) {
                email_is_validated = !(data.is_taken);
            });
        },
    });
});




	</script> -->
    <script type="text/javascript">
    $(document).ready(function () {
        $.ajax({
        url: "/getData/",
        datatype: 'json',
        success: function(data){
            $('tbody').html('')
            var result ='<tr>';
            for(var i = 0; i < data.all_data.length; i++) {
                result += "<th scope='row' class='align-middle text-center'>" + (i+1) + "</th>" +
                "<td class='align-middle text-center'>" + data.all_data[i].nama +"</td>" +
                "<td class='align-middle text-center'>" + data.all_data[i].email +"</td>" +
                "<td class='align-middle text-center'>" + "<a " + "data-email=" + data.all_data[i].email + " class='text-white btn btn-danger unsubscribe-button' float-right role='button' aria-pressed='true'>" + "Unsubscribe" + "</a></td></tr>";
            }
            $('tbody').append(result);
        },
        error: function(error){
            alert("There's no any subcribers yet");
        }
    })

        $('#demo').on('click', 'td .unsubscribe-button', function() {
        var email = $(this).attr('data-email');
        unsubscribe(email);
    });


    });

function unsubscribe(email){
        $.ajax({
            method: "POST",
            url: "/unsubscribe/",
            data: {email: email},
            success: function(){
                $('.unsubBerhasil').show();
                window.location.reload();
            },
        })
    }
    </script>

	<title>Webservice</title>
</head>
<body>
	<header>
		{% include 'website/header.html' %}
	</header>
	<div class="col-sm-12">
        <div class="roundedrec">
            <div class="insiderec">
                <p class="judul">Create Agenda</p>
                <form action="#" method="POST" class="w3-left-align isi" data-validate-email-url="{% url 'validate_email' %}">
                    {% csrf_token %}
                    {% for field in form %}
                        <p>{{ field.label_tag }} {{ field }}</p>
                    {% endfor %}
                    <input type="submit" value="Submit">
                </form> 
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{%static 'website/subscribe.js'%}"></script>

    <p class="judul">List Subscriber</p>
        <div class="table-responsive">
            <div class="unsubBerhasil">Unsubscribing Success</div>
            <table id="demo" class="table" style="font-size: 15px;">
                <thead>
                    <tr class="table text-center">
                        <th scope="col" class="align-middle">No</th>
                        <th scope="col" class="align-middle">Name</th>
                        <th scope="col" class="align-middle">Email</th>
                        <th scope="col" class="align-middle"></th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>

</body>
</html>